# (c) https://github.com/MontiCore/monticore

stages:
- linux

#TestMXNET:
#  stage: linux
#  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/mxnet:v0.0.5
#  script: 
#  - cd mxnet
#  - chmod +x build.sh
#  - ./build.sh
#  - RES=$(./build/src/cpp/DigitCalculator resources/images/1.png resources/images/2.png resources/images/3.png resources/images/4.png resources/images/5.png resources/images/6.png)
#  - "if [[ $RES != *\"SUM: 579\"* ]]; then echo \"Wrong result:\" $RES; exit 1; fi;"


#TestCAFFE2:
#  stage: linux
#  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/caffe2:v0.0.2
#  script: 
#  - cd caffe2
#  - chmod +x build.sh
#  - ./build.sh
#  - RES=$(./build/src/cpp/DigitCalculator resources/images/2.jpg resources/images/3.jpg resources/images/4.png resources/images/6.png resources/images/2.jpg resources/images/3.jpg)
#  - "if [[ $RES != *\"SUM: 857\"* ]]; then echo \"Wrong result:\" $RES; exit 1; fi;"

TestGLUON:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/mxnet:v0.0.5
  script: 
  - cd gluon-cpp
  - chmod +x build.sh
  - ./build.sh
  - RES=$(./build/src/cpp/DigitCalculator resources/images/1.png resources/images/2.png resources/images/3.png resources/images/4.png resources/images/5.png resources/images/6.png)
  - "if [[ $RES != *\"SUM: 579\"* ]]; then echo \"Wrong result:\" $RES; exit 1; fi;"

TestTENSORFLOW:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow
  script:
  - cd tensorflow
  - chmod +x build.sh
  - ./build.sh
  - RES=$(./build/src/cpp/DigitCalculator resources/images/1.png resources/images/2.png resources/images/3.png resources/images/4.png resources/images/5.png resources/images/6.png)
  - "if [[ $RES != *\"SUM: 579\"* ]]; then echo \"Wrong result:\" $RES; exit 1; fi;"

TestMnistCalculator-II:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
  script:
  - mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
  - cd mnist-calculator
  - mvn streamtest:streamtest-build -s settings.xml

TestEMADLMavenPlugin:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
  script:
  - mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
  - cd emadl-maven-plugin
  - mvn dependency:resolve emadl:train -s settings.xml -U 

TestMnistWithAdaNet:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
  script:
    - mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
    - cd AdaNet
    - mvn dependency:resolve emadl:train -s settings.xml

TestMNISTwithCustomLayer:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
  script:
  - shopt -s expand_aliases
  - echo 'alias python='\''/usr/bin/python3'\''' >> ~/.bashrc
  - . ~/.bashrc
  - cat ~/.bashrc
  - echo $PYTHONPATH
  - python --version
  - python3 --version
  - which python
  - which python3
  - alias python=/usr/bin/python3
  - python --version
  - python3 --version
  - which python
  - type -a python
  - mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
  - cd mnist-custom-layer
  - mvn dependency:resolve emadl:train -s settings.xml

InstallONNXTensorflow:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/tensorflow-onnx:latest
  artifacts:
    paths:
    - onnx/tensorflow-pretrained/model/
    expire_in: 1 day
  script:
    - cd onnx/tensorflow-pretrained
    - mvn -v
    - mvn dependency:resolve emadl:train -s settings.xml

