stages:
- windows
- linux
- integration

masterJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
  - cat target/site/jacoco/index.html
  - mvn package sonar:sonar -s settings.xml
  only:
  - master

masterJobWindows:
  stage: windows
  script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
  tags:
  - Windows10

BranchJobLinux:
  stage: linux
  image: maven:3-jdk-8
  artifacts:
    paths:
    - target/generated-sources-cmake/
    - target/generated-sources-ros2/
  script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
  - cat target/site/jacoco/index.html
  except:
  - master

RosIntegrationJob:
  stage: integration
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2middleware/ema-ros-kinetic
  dependencies:
    - BranchJobLinux
  except:
  - master
  script:
  - ./src/test/bash/integrationTestRos.sh

Ros2IntegrationJob:
  stage: integration
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2middleware/ema-ros-crystal
  dependencies:
    - BranchJobLinux
  except:
  - master
  script:
  - ./src/test/bash/integrationTestRos2.sh
