stages:
- windows
- linux
- integration

masterJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
  - cat target/site/jacoco/index.html
  - mvn package sonar:sonar -s settings.xml
  only:
  - master

masterJobWindows:
  stage: windows
  script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
  tags:
  - Windows10

BranchJobLinux:
  stage: linux
  image: maven:3-jdk-8
  artifacts:
    paths:
    - target/generated-sources-cmake/
  script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
  - cat target/site/jacoco/index.html
  except:
  - master

IntegrationJob:
  stage: integration
  image: ros:kinetic
  dependencies:
    - BranchJobLinux
  except:
  - master
  script:
  - apt-get update
  - apt-get install -y openjdk-8-jdk maven wget unzip
  - apt-get install -y g++
  - apt-get install -y libopenblas-dev libhdf5-serial-dev
  - export PATH="/usr/lib/x86_64-linux-gnu/:${PATH}"
  - wget -O /root/armadillo.zip -q --show-progress "https://rwth-aachen.sciebo.de/s/igDWzLpdO5zYHBj/download?path=%2Fubuntu%2F18.10.24-armadillo-linux&files=armadillo-8.500.1-linux.zip"
  - unzip /root/armadillo.zip -d /root/
  - export Armadillo_HOME=/root/armadillo-8.500.1-linux
  - source /opt/ros/kinetic/setup.bash
  - ./src/test/resources/TargetCompilation.sh